# additional data require to create the Docker image
packaging:
  # files to add to the build, usually used with ADD in the Dockerfile
  add:
    # the plugin always filters
    - target/${project.build.finalName}.jar
    - hello-world.yml
# containers that this should be linked to, started before this one and stopped afterwards
links:
  - mysql:db
tag: registry/${project.artifactId}-app:${project.version}

exposeContainerIp: true
